<?xml version="1.0"?>

<robot name="sensor" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="height1" value="0.2" />
  <xacro:property name="width" value="0.2" />
  <xacro:property name="parent" value="gps" />
 <!-- Used for fixing robot to Gazebo 'base_link' -->
  <!-- <link name="${parent}"/> -->

  <joint name="fixed1" type="fixed">
    <parent link="${parent}"/>
    <child link="sensor"/>
  </joint>

 <!-- Base Link -->
  <link name="sensor">
    <collision>
      <origin xyz="-1 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="-1 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="-1 0 1" rpy="0 0 0"/>
      <mass value="0.000001"/>
      <inertia
        ixx="0.000001" ixy="0.0" ixz="0.0"
        iyy="0.000001" iyz="0.0"
        izz="0.000001"/>
    </inertial>
  </link>


  <material name="orange">
    <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
  </material>
 <gazebo reference="sensor">
    <material>Gazebo/Orange</material>
  </gazebo>

</robot>
